apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wallet-service.fullname" . | default "wallet-service" }}
  labels:
    app: wallet-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: wallet-service
  template:
    metadata:
      labels:
        app: wallet-service
    spec:
      containers:
        - name: wallet-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: DATABASE_URL
              value: {{ .Values.env.DATABASE_URL | quote }}
            - name: JWT_AUDIENCE
              value: {{ .Values.env.JWT_AUDIENCE | quote }}
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ .Values.env.OTEL_EXPORTER_OTLP_ENDPOINT | quote }}
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: wallet-service-secrets
                  key: JWT_SECRET
          readinessProbe:
            httpGet:
              path: /v1/ready
              port: {{ .Values.service.port }}
            initialDelaySeconds: 8
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /v1/health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 8
            periodSeconds: 10
          resources:
{{ toYaml .Values.resources | indent 12 }}
