apiVersion: v1
kind: Secret
metadata:
  name: wallet-service-secrets
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.secretEnv.JWT_SECRET | quote }}
  SUPABASE_DB_URL: {{ .Values.secretEnv.SUPABASE_DB_URL | quote }}
  SUPABASE_URL: {{ .Values.secretEnv.SUPABASE_URL | quote }}
  SUPABASE_KEY: {{ .Values.secretEnv.SUPABASE_KEY | quote }}
